Realize02 03 2019
Sofasmile/Homework4 pull request #1
Opened 2019-03-02 18:45 UTC by Sofasmile

2019-03-03 17:00 UTC, Anderwerty requested changes
Fix comments. And look at your .gitignore.

2019-03-03 17:00 UTC, Anderwerty commented on src/com/collection/MyArrayList.java
> +    private void increazeSize() {
Typo. Should be increaseSize

2019-03-03 17:00 UTC, Anderwerty commented on src/com/collection/MyArrayList.java
> +            return null;
It is not a very good solution.  As one or more of elements in the list could be null. It is better to throw the custom exception.

2019-03-03 17:00 UTC, Anderwerty commented on src/com/collection/MyLinkedList.java
> +            System.out.println("Index " + index + " is out of bound!");
The same

2019-03-03 17:00 UTC, Anderwerty commented on src/com/collection/MyLinkedList.java
> +        int oldSize = size;
Do we really need variable `oldSize`?

2019-03-03 17:00 UTC, Anderwerty commented on src/com/collection/MyLinkedList.java
> +            if (iterator == null) {
Is it possible situation when the iterator is null and size>0?

2019-03-03 17:00 UTC, Anderwerty commented on src/com/collection/MyStack.java
> +    int size;
private?

2019-03-03 17:00 UTC, Anderwerty commented on src/com/collection/MyStack.java
> +            if (item == null) {
The same

2019-03-03 19:13 UTC, Sofasmile commented on src/com/collection/MyLinkedList.java
> +        int oldSize = size;
Так, потрібна) Адже при видаленні, size  зменшується на 1, після кожного виклику методу remove(0).

2019-03-04 20:36 UTC, Anderwerty requested changes
Fix comments

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/Node.java
> +    public Node<T> prev;
Why not private? You could use Node as a static inner class in MyLinkedList.

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/MyLinkedList.java
> +    //addLast
Do you need this comment?

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/MyLinkedList.java
> +        last.next = newNode;
It looks like a singly linked list.
Please, read https://habr.com/ru/post/127864/
You don't use Node.prev

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/MyLinkedList.java
> +            throw new Exception("Index is out of bound!");
Please. Create your own Exception. For example NodeIndexOutBoundaryException (extends RuntimeException).

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/MyStack.java
> +            System.out.println("Steck is empty!");
Throw your own exception.

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/MyStack.java
> +            System.out.println("Steck is empty!");
Throw your own exception.

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/MyStack.java
> +            System.out.println("Steck is empty!");
Throw your own exception.

2019-03-04 20:36 UTC, Anderwerty commented on src/com/collection/MyStack.java
> +            System.out.println("Index " + index + " is out of bound!");
Throw your own exception.

2019-03-04 23:03 UTC, Sofasmile commented on src/com/collection/MyLinkedList.java
> +            throw new Exception("Index is out of bound!");
На жаль, не впевнена що правильно створила свої класи exception.

2019-03-05 12:01 UTC, Anderwerty approved these changes
Fix small commetn

2019-03-05 12:01 UTC, Anderwerty commented on src/com/collection/MyLinkedList.java
> +    private Node<T> getNode(int index) throws NodeIndexOutBoundaryException {
If NodeIndexOutBoundaryException extends from RuntimeException you don't need to write throws NodeIndexOutBoundaryException. It is an unchecked exception.

2019-03-05 12:18 UTC, merged